version: '2.4'
name: dripdrop-ui
services:
  web:
    container_name: web
    restart: always
    volumes:
      - ./:/src
    build:
      dockerfile: dockerfiles/Dockerfile.dev.web
    entrypoint: npm run dev -- --port $PORT --host 0.0.0.0
    ports:
      - $PORT:$PORT
